apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopping-cart.fullname" . }}-secret
  labels:
    {{- include "shopping-cart.labels" . | nindent 4 }}
type: Opaque
data:
  database.username: {{ .Values.secret.database.username | b64enc }}
  database.password: {{ .Values.secret.database.password | b64enc }}
  redis.password: {{ .Values.secret.redis.password | b64enc }}
  jwt.secret: {{ .Values.secret.jwt.secret | b64enc }}